include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    # Disable overly strict rules
    always_use_package_imports: false
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    
    # Allow flexibility
    avoid_print: false
    use_build_context_synchronously: false

analyzer:
  errors:
    # Downgrade warnings to info
    invalid_annotation_target: info
    deprecated_member_use: warning
    omit_local_variable_types: ignore
    use_if_null_to_convert_nulls_to_bools: ignore
    
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"